apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Elasticsearch-logs
    type: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    jsonData:
      esVersion: 8
      timeField: "@timestamp"