version: "3.9"

services:
# ─── Core data ─────────────────────────────────────────────
  mongodb:
    image: 'mongo:latest'
    restart: unless-stopped
    environment:
      - 'MONGO_INITDB_DATABASE=content_storage'
      - 'MONGO_INITDB_ROOT_PASSWORD=root'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'

  mongo-express:
    image: 'mongo-express:latest'
    restart: unless-stopped
    container_name: mongo-express
    environment:
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=root'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=root'
      - 'ME_CONFIG_MONGODB_AUTH_DATABASE=admin'
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
    ports:
      - '8081:8081'
    depends_on:
      - mongodb

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes: [ "minio-data:/data" ]
    ports:
      - "9000:9000"
      - "9001:9001"

# ─── Observability stack ──────────────────────────────────
  prometheus:
    image: prom/prometheus:v2.53.5
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.6.3
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./ops/grafana:/etc/grafana/provisioning:ro
    ports:
     - "3000:3000"
    depends_on: [prometheus, elasticsearch]

  jaeger:
    image: jaegertracing/all-in-one:1.71.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "4317:4317"
      - "16686:16686"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m   # впишемся в память
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on: [elasticsearch]

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.0
    user: root              # нужен доступ к /var/lib/docker/containers
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ops/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on: [elasticsearch]
    entrypoint: ["/usr/share/filebeat/filebeat", "-e", "-strict.perms=false"]

volumes:
  minio-data:
  prom-data:
  grafana-data:
  es-data:
