name: Generate OpenAPI Docs

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Make gradlew executable
      run: chmod +x gradlew
    
    - name: Build JAR (skip tests) for api-docs endpoint
      run: ./gradlew -x test bootJar
    
    - name: Start application in background
      run: |
        PORT=$(shuf -i 9000-9999 -n 1)
        echo "PORT=$PORT" >> $GITHUB_ENV
        nohup java -jar build/libs/*.jar --server.port=$PORT > app.log 2>&1 &
        echo $! > app.pid
    
    - name: Wait for application health check
      run: |
        for i in {1..30}; do
          if curl -sf http://localhost:$PORT/actuator/health; then
            echo "Application is ready on port $PORT"
            break
          fi
          echo "Waiting for application... ($i/30)"
          sleep 2
        done
    
    - name: Generate openapi.yaml
      run: ./gradlew -Pspringdoc.url=http://localhost:$PORT/v3/api-docs openapi
    
    - name: Install redoc-cli
      run: npm install -g redoc-cli
    
    - name: Create docs directory
      run: mkdir -p docs
    
    - name: Bundle ReDoc HTML
      run: |
        redoc-cli bundle build/openapi/openapi.yaml -o docs/index.html \
            --title "Content Storage API"
        touch docs/.nojekyll
    
    - name: Stop application
      run: |
        if [ -f app.pid ]; then
          kill $(cat app.pid) || true
        fi
    
    - name: Configure git
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
    
    - name: Commit and push docs
      run: |
        git add docs/index.html docs/.nojekyll
        if git diff --cached --quiet; then
          echo "No API changes"
        else
          git commit -m "docs: update API HTML [skip ci]"
          git push
        fi