name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure docs folder exists
        run: mkdir -p docs

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          # берём сайт из корня и складываем результат в docs
          source: "."
          destination: "docs"
          future: true
          build_revision: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push built docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          if ! git diff --cached --quiet; then
            git commit -m "ci: rebuild Jekyll site [skip ci]"
            git push
          else
            echo "No changes to docs"
          fi